admission/urls.py
from django.urls import path
from admission.views import Index,Account,Profile,StudentProfile,Finance,AdmissionProfilePasswordReset
app_name = 'admission'
urlpatterns = [
    path('',Index.as_view(),name='index'),
    path('account/',Account.as_view(),name='account'),
    path('profile/',Profile.as_view(),name='profile'),
    path('student/',StudentProfile.as_view(),name='student-profile'),
    path('finance/',Finance.as_view(),name='finance'),
    path('passreset/',AdmissionProfilePasswordReset.as_view(),name='profile-reset')
]

authsystem/urls.py
from django.urls import path
from authsystem.views import Index,Info,user_logout

app_name='authsystem'

urlpatterns = [
    path('', Index.as_view(), name='authsystem_index'),
    path('info/',Info.as_view(),name='authsystem_info'),
    path('logout/',user_logout,name='authsystem_logout')
]

dean/urls.py
from django.urls import path
from dean.views import (
    Index,AdmissionApproval,AdmissinApprovalLink,
    CourseDetails,FinanceApprove,FinanceApproval,
    EditCourse,DeanNewStaff
)
app_name = 'dean'

urlpatterns = [
    path('',Index.as_view(),name='index'),
    path('admission/',AdmissionApproval.as_view(),name='admission'),
    path('admissionapr/<str:u_name>/',AdmissinApprovalLink.as_view(),name='admission_apr_link'),
    path('courses/',CourseDetails.as_view(),name='course'),
    path('finance/',FinanceApprove.as_view(),name='financestaff'),
    path('financeapr/<int:pk>/',FinanceApproval.as_view(),name='financeapproval'),
    path('editcourse/<int:pk>/',EditCourse.as_view(),name='edit-course'),
    path('newstaff/',DeanNewStaff.as_view(),name='staff')
]

xms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authsystem.urls')),
    path('student/',include('student.urls')),
    path('admission/',include('admission.urls')),
    path('clgstaff/',include('clgstaff.urls')),
    path('exam/',include('exam.urls')),
    path('finance/',include('finance.urls')),
    path('prof/',include('prof.urls')),
    path("sitemanager/",include('sitemanager.urls')),
    path('dean/',include('dean.urls'))
]

dean/models.py
from django.db import models
from authsystem.models import CustomUser

# Create your models here.


class DeanSalary(models.Model):
    salary_date = models.DateField()
    salary_ammount = models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return f'self.id'


class DeanDepartment(models.Model):
    firstname = models.CharField(max_length=255)
    middlename = models.CharField(max_length=255,blank=True)
    lastname = models.CharField(max_length=255)

    date_of_birth = models.DateField()
    mobile = models.CharField(max_length=10)
    emergency_mobile = models.CharField(max_length=10)
    
    present_address = models.CharField(max_length=255)
    present_city = models.CharField(max_length=255)
    present_state = models.CharField(max_length=255)
    present_zip = models.IntegerField()

    permanent_address = models.CharField(max_length=255)
    permanent_city = models.CharField(max_length=255)
    permanent_state = models.CharField(max_length=255)
    permanent_zip = models.IntegerField()
    account_type = models.CharField(default='dean',max_length=255)
    package_lpa = models.DecimalField(max_digits=10,decimal_places=2,default=0.0)
    salary = models.ForeignKey(DeanSalary,on_delete = models.CASCADE,null= True,related_name='dean_salary')
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE,null=True,related_name='dean')
    def __str__(self):
        return f'{self.firstname} {self.lastname}'

dean/forms.py
from django import forms
from dean.models import DeanDepartment


class DeanDepartmentForm(forms.ModelForm):

    class Meta:

        model = DeanDepartment

        exclude = ('user','salary','account_type')

        widgets = {
            'firstname':forms.TextInput(attrs={'placeholder':
            'First Name','class':'form-control'}),
            'middlename':forms.TextInput(attrs={'placeholder':
            'Middle Name','class':'form-control'}),
            'lastname':forms.TextInput(attrs={'placeholder':
            'Last Name','class':'form-control'}),
            'date_of_birth':forms.DateInput(attrs={'type':'date','class':'form-control'}),
            'mobile':forms.TextInput(attrs={'placeholder':
            'Mobile Number','class':'form-control'}),
            'emergency_mobile':forms.TextInput(attrs={'placeholder':
            'Emergency Mobile Number','class':'form-control'}),
            'present_address':forms.TextInput(attrs={'placeholder':
            'Present Address','class':'form-control'}),
            'present_city':forms.TextInput(attrs={'placeholder':
            'Present City','class':'form-control'}),
            'present_state':forms.TextInput(attrs={'placeholder':
            'Present State','class':'form-control'}),
            'present_zip':forms.TextInput(attrs={'placeholder':
            'Present Zip Code','class':'form-control'}),
            'permanent_address':forms.TextInput(attrs={'placeholder':
            'Permanent Address','class':'form-control'}),
            'permanent_city':forms.TextInput(attrs={'placeholder':
            'Permanent City','class':'form-control'}),
            'permanent_state':forms.TextInput(attrs={'placeholder':
            'Permanent State','class':'form-control'}),
            'permanent_zip':forms.TextInput(attrs={'placeholder':
            'Permanent Zip Code','class':'form-control'}),
            'package_lpa':forms.TextInput(attrs={'placeholder':
            'CTC LPA','class':'form-control'}),
        }

dean/views.py
from django.shortcuts import render,redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from dean.decorators import dean_required
from django.views import View
from admission.models import AdmissionDepart
from authsystem.models import CustomUser
from django.contrib import messages
from student.forms import CourseForm
from student.models import Course
from django.db.models import Q
from dean.forms import DeanDepartmentForm
from django.contrib.auth.models import Group
class Index(View):

    @method_decorator(login_required)
    @method_decorator(dean_required)
    def get(self,request):
        return render(request,'dean/index.html',{})

class AdmissionApproval(View):

    @method_decorator(login_required)
    @method_decorator(dean_required)
    def get(self,request):
        user_names = CustomUser.object.filter(Q(is_active = False) & Q(groups__name__in=['admission','admission manager']))
        admission_list = []
        for f in user_names:
            admission = AdmissionDepart.objects.get(user = f)
            admission_list.append(admission)
        return render(request,'dean/admission_approve.html',{'user_names':admission_list})

class AdmissinApprovalLink(View):

    @method_decorator(login_required)
    @method_decorator(dean_required)
    def get(self,request,u_name):
        user_object = CustomUser.object.get(username = u_name)
        if user_object.is_active == False:
            user_object.is_active = True
            user_object.save()
            messages.success(request,"Profile approved successfully.")
            return redirect('dean:admission')
        else:
            messages.info(request,"Profile is already approved successfully.")
            return redirect('dean:admission')


class CourseDetails(View):

    @method_decorator(login_required)
    @method_decorator(dean_required)
    def get(self,request):
        courses = Course.objects.all()
        form = CourseForm()
        return render(request,'dean/course.html',{'courses':courses,'form':form})
    
    def post(self,request):
        form_data = CourseForm(request.POST)
        if form_data.is_valid():
            form_data.save()
            messages.success(request,"Course Added Successfully")
        else:
            messages.error(request,"Unable to add course")
        
        return redirect('dean:course')
    
class FinanceApprove(View):

    @method_decorator(login_required)
    @method_decorator(dean_required)
    def get(self,request):
        user_names = CustomUser.object.filter(Q(is_active = 0) & Q(groups__name__in=['finance','finance manager']))
        return render(request,'dean/financeapproval.html',{'user_names':user_names})
class FinanceApproval(View):
    @method_decorator(login_required)
    @method_decorator(dean_required)
    def get(self,request,pk):
        try:
            user_name = CustomUser.object.get(pk=pk)
            user_name.is_active = True
            user_name.save()
            messages.success(request,'Profile Activate Successfully')
        except:
            messages.error(request,'Unable to Activate Profile')
        return redirect('dean:financestaff')

class EditCourse(View):
    @method_decorator(login_required)
    @method_decorator(dean_required)
    def get(self,request,pk):
        try:
            data = Course.objects.get(pk=pk)
        except:
            data = None
        return render(request,'dean/editcourse.html',{'data':data})

    
    @method_decorator(login_required)
    @method_decorator(dean_required)
    def post(self,request,pk):
        course_name = request.POST.get('course-name',None)
        course_duration = request.POST.get('course-duration',None)
        course_description = request.POST.get('course-description',None)
        course_fee = request.POST.get('course-fee',None)

        if course_name and course_duration and course_description and course_fee:
            try:
                course_details = Course.objects.get(pk=pk)
                course_details.name = course_name
                course_details.description = course_description
                course_details.duration = course_duration
                course_details.fee = course_fee
                course_details.save()
                return redirect('dean:course')
            except:
                return redirect('dean:course')
        else:
            return redirect('dean:course')


class DeanNewStaff(View):
    
    @method_decorator(login_required)
    @method_decorator(dean_required)
    def get(self,request):
        form = DeanDepartmentForm()
        return render(request,'dean/newstaff.html',{'form':form})

    @method_decorator(login_required)
    @method_decorator(dean_required)
    def post(self,request):
        form_data = DeanDepartmentForm(request.POST)
        if form_data.is_valid():
            form_object = form_data.save()
            f_name = form_object.firstname
            l_name = form_object.lastname
            i_name = form_object.id
            mob = form_object.mobile
            dob = form_object.date_of_birth.year
            user_object = CustomUser.object.create_user(
                username=f'{f_name[:5].lower()}{l_name[:5].lower()}d{i_name}',
                password = f'{str(mob)[:5]}@{dob}',
                is_active = True
            )
            user_object.groups.add(Group.objects.get(name='dean'))
            form_object.user = user_object
            form_object.account_type = 'dean'
            form_object.save()
            messages.success(request,f'Profile created successfully : username {f_name[:5].lower()}{l_name[:5].lower()}d{i_name}')
        else:
            print("something is wrong")
        return redirect('dean:staff')

dean/templates/dean/admission_approve.html
{% extends 'dean/base.html' %}
{% block title %}Approve Admission Staff{% endblock %}
{% block admission %}active {% endblock %}
{% block body %}
    {% if user_names %} 
    <div class="container">
        <div class="alert alert-info mb-5 mt-5" role="alert">
            <h1 class="display-3 text-center">Please approve the below profile</h1>
        </div>
            {% include 'dean/msg.html' %}
        <table class="table">
            <thead>
              <tr>
                <th scope="col">User Name</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Salary LPA</th>
                <th scope="col">Profile</th>
                <th scope="col">Approve</th>
              </tr>
            </thead>
            <tbody>
              {% for u in user_names %}
                <tr>
                  <th scope="row">{{u.user}}</th>
                  <td>{{u.firstname}}</td>
                  <td>{{u.lastname}}</td>
                  <td>{{u.package_lpa}}</td>
                  {% if u.account_type == 'admission manager' %}
                    <td>Manager</td>
                  {% else %}
                    <td>Staff</td>
                  {% endif %}
                  <td><a href="{% url 'dean:admission_apr_link' u.user %}" class="btn btn-success">Approve </a></td>
                </tr>
              {% endfor %}
            </tbody>
        </table>
      </div>
    {% else %}
    <div class="container">
        <div class="alert alert-primary mb-5 mt-5 text-center display-6" role="alert">
            No pending approval
        </div>
    </div>
    {% endif %}

{% endblock %}

dean/templates/dean/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title%} {% endblock %}</title>
  </head>
  <body>
    <!-- Navbar for Dean -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'dean:index' %}">Dean Portal</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% block admission %} {% endblock %}" href="{% url 'dean:admission' %}">Admission Staff Approve</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block finance %} {% endblock %}" href="{% url 'dean:financestaff' %}">Finance Staff Approve</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block staff %} {% endblock %}" href="{% url 'dean:staff' %}">New Staff</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block course %} {% endblock %}" href="{% url 'dean:course' %}">Courses</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block pay %} {% endblock %}" href="{% url 'admission:finance' %}">Pay Portal</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block profile %} {% endblock %}" href="{% url 'admission:profile' %}">Profile</a>
              </li>
              <li class="nav-item mr-auto">
                <a class="btn btn-danger" href="{% url 'authsystem:authsystem_logout' %}">Logout</a>
              </li>
            </ul>
        </div>
      </nav>
    <!-- Navbar End for Dean-->

    {% block body %}
    {% endblock %}
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

dean/templates/dean/course.html
{% extends 'dean/base.html' %}
{% block course %}active{% endblock %}
{% block title %}XYZ College{% endblock %}
{% block body %}

{% include 'dean/msg.html' %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-5">
                <div class="alert alert-info" role="alert">
                    <h1 class="display-6 text-center">
                        Add New Course
                    </h1>
                  </div>
                <form class="alert alert-dark" action="{% url 'dean:course' %}" method="POST">
                    {% csrf_token %}
                    {% for f in form %}

                    <div class="mb-3">
                        {{f}}
                     </div>
                     {% endfor %}
                    <center>
                        <button type="submit" class="btn btn-primary">Add New Course</button>
                    </center>
                </form>
            </div>
            <div class="col-md-7">
                <div class="alert alert-primary" role="alert">
                    <h1 class="display-6 text-center">Courses</h1>
            
                </div>
                {% if courses %}

                <table class="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Course Name</th>
                        <th scope="col">Course Duration</th>
                        <th scope="col">Course Fee</th>
                        <th scope="col">Edit</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for course in courses %}
                      <tr>
                        <th scope="row">{{course.id}}</th>
                        <td>{{course.name}}</td>
                        <td>{{course.duration}}</td>
                        <td>{{course.fee}}</td>
                        <td><a href="{% url 'dean:edit-course' course.id %}" class="btn btn-primary">Edit</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                {% else %}
                    <h1 class="text-center mt-4">
                        Course not yet added.
                    </h1>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

dean/templates/dean/editcourse.html
{% extends 'dean/base.html' %}
{% block title %}XYZ College{% endblock %}
{% block body %}
    {% include 'dean/msg.html' %}
    {% if data %}
    <div class="container">
        <div class="alert alert-primary text-center display-6 mb-5 mt-5" role="alert">
            Course Details
        </div>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Values</th>
                <th scope="col">Course Name</th>
                <th scope="col">Course Description</th>
                <th scope="col">Course Duration</th>
                <th scope="col">Course Fee</th>
            </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">Old Value</th>
                <td>{{data.name}}</td>
                <td>{{data.description}}</td>
                <td>{{data.duration}} Years</td>
                <td>{{data.fee}}</td>
              </tr>
              <form action="{% url 'dean:edit-course' data.id %}" method="POST">
                {% csrf_token %}
              <tr>
                <th scope="row">New Value</th>
                <td><input type="text" name="course-name" placeholder="Course Name" class="form-control" value={{data.name}} /></td>
                <td><input type="text" name="course-description" placeholder="Course Description" class="form-control" value={{data.description}} /></td>
                <td><input type="number" name="course-duration" placeholder="Course Duration" class="form-control" value={{data.duration}} /></td>
                <td><input type="number" name="course-fee" placeholder="Course Tution Fee" class="form-control" value={{data.fee}} /></td>
              </tr>
              <tr>
                <td colspan=5><center class="mt-3 mb-3"><input type="submit" value="Update Course Details" class="btn btn-success" /></center></td>
              </tr>
            </form>
            </tbody>
          </table>
        
    </div>
    {% else %}
        
    {% endif%}
{% endblock %}

dean/templates/dean/financeapproval.html
{% extends 'dean/base.html' %}
{% block title %}Approve Admission Staff{% endblock %}
{% block finance %}active {% endblock %}
{% block body %}

    {% if messages %}
        <div class="container">
            <center>
                {% for message in messages %}
                    <h1 class="display-6 mt-5 mb-5 text-center">{{message}}</h1>
                {% endfor %}
            </center>
        </div>
    {% endif %}
    {% if user_names %}
    <div class="container mt-5 mb-5">
        <div class="alert alert-primary text-center display-6" role="alert">
            Approval Required for Finance Staff / Manager
        </div>
        <table class="table mt-5">
            <thead>
              <tr>
                <th scope="col">User Name</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Salary LPA</th>
                <th scope="col">Profile</th>
                <th scope="col">Approve</th>
              </tr>
            </thead>
            <tbody>
              {% for u in user_names %}
                <tr>
                  <th scope="row">{{u.finance.user}}</th>
                  <td>{{u.finance.firstname}}</td>
                  <td>{{u.finance.lastname}}</td>
                  <td>{{u.finance.package_lpa}}</td>
                  {% if u.finance.account_type == 'finance manager' %}
                    <td>Manager</td>
                  {% else %}
                    <td>Staff</td>
                  {% endif %}
                  <td><a href="{% url 'dean:financeapproval' u.id %}" class="btn btn-success">Approve </a></td>
                </tr>
              {% endfor %}
            </tbody>
        </table>

    </div>
    {% else %}
        <div class="container mt-5 mb-5">
            <div class="alert alert-primary text-center display-6" role="alert">
                No Pending Approval
            </div>
        </div>
    {% endif %}
{% endblock %}

dean/templates/dean/index.html
{% extends 'dean/base.html' %}
{% block title %}XYZ College{% endblock %}
{% block body %}
    <center><h1>Welcome to Dean Portal</h1></center>
    <center><h1>Last login time : {{request.session.last_stamp}}</center>
    <center><a href="{% url 'authsystem:authsystem_logout' %}" class="btn btn-danger" >Logout</a></center>

{% endblock %}

dean/templates/dean/msg.html
{% if messages %}
    <div class="container">
        {% for message in messages %}
        <div class="{{ message.tags}} text-center mb-3 mt-3" role="alert">
            {{message}}
        </div>
    {% endfor %}
    </div>
{% endif %}

dean/templates/dean/newstaff.html
{% extends 'dean/base.html' %}
{% block title %}Register Staff{% endblock %}
{% block staff %}active {% endblock %}
{% block body %}

{% if messages %}
        <div class="container mb-5 mt-5">
            <center>
                {% for message in messages %}
                    {{message}}
                {% endfor %}
            </center>
        </div>
    {% endif %}
    <center><h1 class="display-5 mt-5">Register a new Dean Staff</h1></center>
    <div class="container mt-5 mb-5">
        <center class="shadow-lg p-3 mb-5 bg-body rounded">
            <form action="{% url 'dean:staff' %}" method="POST">
                {% csrf_token %}
                <table class="table table-striped">
                    <tbody>
                        {% for field in form %}
                        <tr>
                            <th>{{field.label_tag}}</th>
                            <td>{{field}}</td>
                          </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                  <input type="submit" value="Register" class="btn btn-success">
            </form>
        </center>
    </div>
   
{% endblock %}