admission/urls.py
from django.urls import path
from admission.views import Index,Account,Profile,StudentProfile,Finance,AdmissionProfilePasswordReset
app_name = 'admission'
urlpatterns = [
    path('',Index.as_view(),name='index'),
    path('account/',Account.as_view(),name='account'),
    path('profile/',Profile.as_view(),name='profile'),
    path('student/',StudentProfile.as_view(),name='student-profile'),
    path('finance/',Finance.as_view(),name='finance'),
    path('passreset/',AdmissionProfilePasswordReset.as_view(),name='profile-reset')
]

authsystem/urls.py
from django.urls import path
from authsystem.views import Index,Info,user_logout

app_name='authsystem'

urlpatterns = [
    path('', Index.as_view(), name='authsystem_index'),
    path('info/',Info.as_view(),name='authsystem_info'),
    path('logout/',user_logout,name='authsystem_logout')
]

finance/urls.py
from django.urls import path
from finance.views import(
    Index,FinanceProfile,AccountProfile,StudentProfile,StudentActivate,AcceptFee,
    SearchStudent,
) 


app_name = 'finance'
urlpatterns = [
    path('',Index.as_view(),name='index'),
    path('profile/',FinanceProfile.as_view(),name='profile'),
    path('account/',AccountProfile.as_view(),name='account'),
    path('studentprofile/',StudentProfile.as_view(),name='studentprofile'),
    path('studentactivate/<int:pk>/',StudentActivate.as_view(),name='studentactivate'),  
    path('feepayment/',AcceptFee.as_view(),name='payment'), 
    path('searchstudent/',SearchStudent.as_view(),name='search_student'),
]

xms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authsystem.urls')),
    path('student/',include('student.urls')),
    path('admission/',include('admission.urls')),
    path('clgstaff/',include('clgstaff.urls')),
    path('exam/',include('exam.urls')),
    path('finance/',include('finance.urls')),
    path('prof/',include('prof.urls')),
    path("sitemanager/",include('sitemanager.urls')),
    path('dean/',include('dean.urls'))
]

admission/models.py
from django.db import models
from authsystem.models import CustomUser

#Creating model for registering a new memeber in admission department
#Admission Staff Model


class AdmissionSalalry(models.Model):
    salary_date = models.DateField()
    salary_ammount = models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return f'self.id'
class AdmissionDepart(models.Model):
    firstname = models.CharField(max_length=255)
    middlename = models.CharField(max_length=255,blank=True)
    lastname = models.CharField(max_length=255)

    date_of_birth = models.DateField()
    mobile = models.CharField(max_length=10)
    emergency_mobile = models.CharField(max_length=10)
    
    present_address = models.CharField(max_length=255)
    present_city = models.CharField(max_length=255)
    present_state = models.CharField(max_length=255)
    present_zip = models.IntegerField()

    permanent_address = models.CharField(max_length=255)
    permanent_city = models.CharField(max_length=255)
    permanent_state = models.CharField(max_length=255)
    permanent_zip = models.IntegerField()
    account_type = models.CharField(default='',max_length=255)
    package_lpa = models.DecimalField(max_digits=10,decimal_places=2,default=0.0)
    salary = models.ForeignKey(AdmissionSalalry,on_delete = models.CASCADE,null= True)
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE,null=True,related_name='admission')
    def __str__(self):
        return f'{self.firstname} {self.lastname}'

admission/forms.py
from admission.models import AdmissionDepart
from django import forms

ACCOUNT_TYPE = (
    ("admission","Staff"),
    ("admission manager","Manager"),
)
class AdmissionDepartmentForm(forms.ModelForm):

    account_type = forms.ChoiceField(label='Account Type' , choices=ACCOUNT_TYPE,widget=forms.Select(attrs={'class':'form-control mb-2'}))
    class Meta:
        model = AdmissionDepart
        # fields = '__all__'
        exclude = ['user','salary']

        widgets = {
            'firstname':forms.TextInput(attrs={'placeholder':
            'First Name','class':'form-control mb-2'}),
            'middlename':forms.TextInput(attrs={'placeholder':
            'Middle Name','class':'form-control mb-2'}),
            'lastname':forms.TextInput(attrs={'placeholder':
            'Last Name','class':'form-control mb-5'}),
            'date_of_birth':forms.DateInput(attrs={'type':'date','class':'form-control mb-5','placeholder':'Date of Birth','onfocus':"(this.type='date')",'onblur':"(this.type='text')"}),
            'mobile':forms.TextInput(attrs={'placeholder':
            'Mobile Number','class':'form-control mb-2'}),
            'emergency_mobile':forms.TextInput(attrs={'placeholder':
            'Emergency Mobile Number','class':'form-control mb-5'}),
            'present_address':forms.TextInput(attrs={'placeholder':
            'Present Address','class':'form-control mb-2'}),
            'present_city':forms.TextInput(attrs={'placeholder':
            'Present City','class':'form-control mb-2'}),
            'present_state':forms.TextInput(attrs={'placeholder':
            'Present State','class':'form-control mb-2'}),
            'present_zip':forms.TextInput(attrs={'placeholder':
            'Present Zip Code','class':'form-control mb-5'}),
            'permanent_address':forms.TextInput(attrs={'placeholder':
            'Permanent Address','class':'form-control mb-2'}),
            'permanent_city':forms.TextInput(attrs={'placeholder':
            'Permanent City','class':'form-control mb-2'}),
            'permanent_state':forms.TextInput(attrs={'placeholder':
            'Permanent State','class':'form-control mb-2'}),
            'permanent_zip':forms.TextInput(attrs={'placeholder':
            'Permanent Zip Code','class':'form-control mb-5'}),
            'package_lpa':forms.TextInput(attrs={'placeholder':
            'CTC LPA','class':'form-control mb-5'}),
        }

finance/forms.py
from django import forms 
from finance.models import FinanceDepartment

ACCOUNT_TYPE = (
    ("finance","Staff"),
    ("finance manager","Manager"),
)

class FinanceForm(forms.ModelForm):
    account_type = forms.ChoiceField(label='Account Type' , choices=ACCOUNT_TYPE,widget=forms.Select(attrs={'class':'form-control mb-2'}))
    class Meta:
        model = FinanceDepartment
        exclude = ('user','salary')

        widgets = {
            'firstname':forms.TextInput(attrs={'placeholder':
            'First Name','class':'form-control mb-2'}),
            'middlename':forms.TextInput(attrs={'placeholder':
            'Middle Name','class':'form-control mb-2'}),
            'lastname':forms.TextInput(attrs={'placeholder':
            'Last Name','class':'form-control mb-5'}),
            'date_of_birth':forms.DateInput(attrs={'type':'date','class':'form-control mb-5'}),
            'mobile':forms.TextInput(attrs={'placeholder':
            'Mobile Number','class':'form-control mb-2'}),
            'emergency_mobile':forms.TextInput(attrs={'placeholder':
            'Emergency Mobile Number','class':'form-control mb-5'}),
            'present_address':forms.TextInput(attrs={'placeholder':
            'Present Address','class':'form-control mb-2'}),
            'present_city':forms.TextInput(attrs={'placeholder':
            'Present City','class':'form-control mb-2'}),
            'present_state':forms.TextInput(attrs={'placeholder':
            'Present State','class':'form-control mb-2'}),
            'present_zip':forms.TextInput(attrs={'placeholder':
            'Present Zip Code','class':'form-control mb-5'}),
            'permanent_address':forms.TextInput(attrs={'placeholder':
            'Permanent Address','class':'form-control mb-2'}),
            'permanent_city':forms.TextInput(attrs={'placeholder':
            'Permanent City','class':'form-control mb-2'}),
            'permanent_state':forms.TextInput(attrs={'placeholder':
            'Permanent State','class':'form-control mb-2'}),
            'permanent_zip':forms.TextInput(attrs={'placeholder':
            'Permanent Zip Code','class':'form-control mb-5'}),
            'package_lpa':forms.TextInput(attrs={'placeholder':
            'CTC LPA','class':'form-control mb-5'}),
        }

admission/views.py
from django.contrib import messages
from django.shortcuts import render,redirect
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from admission.decorators import admission_required,admission_manager_requried
from admission.forms import AdmissionDepartmentForm
from authsystem.models import CustomUser
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate,login
from student.forms import StudentForm

class Index(View):
    @method_decorator(login_required)
    @method_decorator(admission_required)
    def get(self,request):
        return render(request,'admission/index.html',{})

class Account(View):
    @method_decorator(login_required)
    @method_decorator(admission_manager_requried)
    def get(self,request):
        form = AdmissionDepartmentForm()
        return render(request,'admission/account.html',{'form':form})

    @method_decorator(login_required)
    @method_decorator(admission_manager_requried)
    def post(self,request):
        form_data = AdmissionDepartmentForm(request.POST)
        if form_data.is_valid():
            form_object = form_data.save()
            f_name = form_object.firstname
            l_name = form_object.lastname
            i_name = form_object.id
            mob = form_object.mobile
            dob = form_object.date_of_birth.year
            user_object = CustomUser.object.create_user(
                username=f'{f_name[:5].lower()}{l_name[:5].lower()}{i_name}',
                password = f'{str(mob)[:5]}@{dob}',
            )
            user_object.groups.add(Group.objects.get(name=form_data.account_type))
            form_object.user = user_object
            form_object.save()
            messages.success(request,f'Profile created successfully : username {f_name[:5].lower()}{l_name[:5].lower()}{i_name}')
        else:
            print("something is wrong")
        return redirect('admission:account')

class Finance(View):
    @method_decorator(login_required)
    @method_decorator(admission_required)
    def get(self,request):
        return render(request,'admission/finance.html',{})

class Profile(View):
    @method_decorator(login_required)
    @method_decorator(admission_required)
    def get(self,request):
        return render(request,'admission/profile.html',{})

class StudentProfile(View):
    @method_decorator(login_required)
    @method_decorator(admission_required)
    def get(self,request):
        form = StudentForm()
        return render(request,'admission/studentprofile.html',{'form':form})

    @method_decorator(login_required)
    @method_decorator(admission_required)
    def post(self,request):
        form_data = StudentForm(request.POST)
        print('got the data')
        if form_data.is_valid():
            form_object = form_data.save()
            print('data saved')
            f_name = form_object.firstname
            l_name = form_object.lastname
            i_name = form_object.id
            mob = form_object.mobile
            dob = form_object.date_of_birth.year
            user_object = CustomUser.object.create_user(
                username=f'{f_name[:5].lower()}{l_name[:5].lower()}s{i_name}',
                password = f'{str(mob)[:5]}@{dob}'
            )
            print('profile creatd')
            user_object.groups.add(Group.objects.get(name='student'))
            print("group added")
            form_object.user = user_object
            form_object.save()
            print("Profiel saved")
            messages.success(request,f'Student profile created successfully : username {f_name[:5].lower()}{l_name[:5].lower()}s{i_name}')
        else:
            print("something is wrong")
        return redirect('admission:student-profile')

class AdmissionProfilePasswordReset(View):
    @method_decorator(login_required)
    @method_decorator(admission_required)
    def post(self,request):
        old_password = request.POST.get('old_password',None)
        new_password = request.POST.get('new_password',None)
        if old_password is not None and new_password is not None:
            user_id = authenticate(username=request.user.username,password=old_password)
            if user_id is not None:
                user_id.set_password(new_password)
                user_id.save()
                login(request,user_id)
                messages.success(request,'Password changed successfully')
            else:
                messages.error(request,'Failed to change the password, try again')
        return redirect('admission:profile')
        

finance/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from finance.decorators import finance_required,finance_manager_required
from student.models import Student,CourseFee
from django.db.models import Q
from authsystem.models import CustomUser
from finance.forms import FinanceForm
from django.contrib.auth.models import Group
from django.contrib import messages
from datetime import datetime
class Index(View):
    @method_decorator(login_required)
    @method_decorator(finance_required)
    def get(self,request):
        return render(request,'finance/base.html',{})

class FinanceProfile(View):
    @method_decorator(login_required)
    @method_decorator(finance_required)
    def get(self,request):
        return render(request,'finance/profile.html',{})

class AccountProfile(View):
    @method_decorator(login_required)
    @method_decorator(finance_manager_required)
    def get(self,request):
        form = FinanceForm()
        return render(request,'finance/Account.html',{'form':form})

    @method_decorator(login_required)
    @method_decorator(finance_manager_required)
    def post(self,request):
        form_data = FinanceForm(request.POST)
        if form_data.is_valid():
            form_object = form_data.save()
            f_name = form_object.firstname
            l_name = form_object.lastname
            i_name = form_object.id
            mob = form_object.mobile
            dob = form_object.date_of_birth.year
            user_object = CustomUser.object.create_user(
                username=f'{f_name[:5].lower()}{l_name[:5].lower()}f{i_name}',
                password = f'{str(mob)[:5]}@{dob}'
            )
            user_object.groups.add(Group.objects.get(name=form_object.account_type))
            form_object.user = user_object
            form_object.save()
            messages.success(request,f'Profile created successfully : username {f_name[:5].lower()}{l_name[:5].lower()}f{i_name}')
        else:
            print("something is wrong")
        return redirect('finance:account')

class StudentProfile(View):
    @method_decorator(login_required)
    @method_decorator(finance_required)
    def get(self,request):
        # fetching all the student object who are not yet active
        student_names = CustomUser.object.filter(Q(is_active = False) & Q(groups__name='student'))
        return render(request,'finance/studentprofile.html',{'students':student_names}) 
    
class StudentActivate(View):
    @method_decorator(login_required)
    @method_decorator(finance_required)
    def get(self,request,pk):
        user_data = CustomUser.object.get(pk=pk)
        fee_details = CourseFee.objects.filter(student=user_data)
        total_fee = 0
        if fee_details.exists:
            for fee in fee_details:
                total_fee += fee.ammount
        return render(request,'finance/student_pay.html',{'user_data':user_data,'fee_paid':total_fee})


class AcceptFee(View):

    @method_decorator(login_required)
    @method_decorator(finance_required)
    def post(self,request):
        id = request.POST.get('id',None)
        fee = request.POST.get('fee',None)
        if id is not None and fee is not None:
            try:
                user_data = CustomUser.object.get(pk=id)
            except:
                messages.error(request,'Error')

            fee_object = CourseFee(student=user_data,date=datetime.now(),ammount=fee)
            fee_object.save()
            if user_data.is_active == 0:
                user_data.is_active = 1
                user_data.save()
            messages.success(request,'Data Saved Successfully')    

        return redirect('finance:studentactivate',pk=id)


class SearchStudent(View):
    def post(self,request):
        search_data = request.POST.get('search',None)
        data = Student.objects.filter(Q(firstname__in=search_data.split())| Q(lastname__icontains=search_data) | Q(id__icontains = search_data.split()) | Q(mobile = search_data) | Q(user__username__icontains=search_data))
        return render(request,'finance/student_search.html',{'data':data})

admission/templates/admission/account.html
{% extends 'admission/base.html' %}
{% block title %}Admission Portal{% endblock title%}
{% block staff%}active{% endblock staff%}
{% block body %}
    <center><h1 class="display-5">Register New Staff</h1></center>
    <div class="mb-4 mt-4 container">
        <center>
            {% include 'admission/msg.html' %}
        </center>
    </div>
    <center>
        <div class="card shadow-lg p-3 mb-5 bg-body rounded" style="width: 40rem;">
            <div class="card-body">
                <form action="{% url 'admission:account' %}" method="POST">
                    {% csrf_token %}
                    {% for f in form %}
                        {{f}}
                    {% endfor %}
                    <button type="submit" class="btn btn-success">Create Profile </button>
                </form>
            </div>
          </div>
    </center>

    <center>
        

    </center>
{%endblock body %}

admission/templates/admission/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock%}</title>
  </head>
  <body>
    <!-- Nav Bar for Admission Portal -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'admission:index' %}">Admission</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% block student %} {% endblock %}" href="{% url 'admission:student-profile' %}">New Student</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block staff %} {% endblock %}" href="{% url 'admission:account' %}">New Staff</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block pay %} {% endblock %}" href="{% url 'admission:finance' %}">Pay Portal</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block profile %} {% endblock %}" href="{% url 'admission:profile' %}">Profile</a>
              </li>
              <li class="nav-item mr-auto">
                <a class="btn btn-danger" href="{% url 'authsystem:authsystem_logout' %}">Logout</a>
              </li>
            </ul>
        </div>
      </nav>
    <!-- Navbar tag ended here-->

    <!-- Dynamic Render of HTML Body -->
    {% block body %}
    {% endblock %}
    <!-- End of Dynamic Render of HTML Body -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

admission/templates/admission/finance.html
{% extends 'admission/base.html' %}
{% block title %}Finance Portal{% endblock title%}
{% block finance%}active{% endblock finance%}
{% block body %}
    <center><h1 class="display-5">Finace Portal</h1></center>
{%endblock body %}

admission/templates/admission/index.html
{% extends 'admission/base.html' %}
{% block title %}Admission Portal{% endblock title%}
{% block body %}
{% include 'admission/msg.html' %}
    <center><h1 class="display-5">Index Page</h1></center>
{%endblock body %}

admission/templates/admission/msg.html
{% if messages %}
    {% for message in messages %}
        <center>
            <div class="container mb-3 mt-3">
                <div class="{{message.tags}}" role="alert">
                    {{message}}
                </div>
            </div>
        </center>
    {% endfor %}
{% endif %}

admission/templates/admission/profile.html
{% extends 'admission/base.html' %}
{% block title %}Finance Portal{% endblock title%}
{% block profile%}active{% endblock profile%}
{% block body %}
    <div class="container">
        {% include 'admission/msg.html' %}
        <ul class="list-group mt-5 p-5">
            <li class="list-group-item ml-5">
                <h1 class="display-6 mb-5">
                    Account Information
                </h1>
                <div class="vr">
                    <h4>User Name <span class="badge bg-secondary">{{request.user.username}}</span></h4>
                <table>
                    <tr>
                        <td class="mr-4">
                            <h5 class="mt-3 mr-4">Change Password</h5>
                        </td>
                        <form method="POST" action="{% url 'admission:profile-reset' %}">
                            {% csrf_token %}
                            <td>
                                <input type="password" name="old_password" class="form-control" style="width:250px" placeholder="Old Password" />
                            </td>
                            <td>
                                <input type="password" name="new_password" class="form-control" style="width:250px" placeholder="New Password" />
                            </td>
                            <td>
                                <input type="submit" class="btn btn-success" value="Change Password"/>
                            </td>
                        </form>
                    </tr>
                </table>
                </div>
            </li>
            <li class="list-group-item">
                <h1 class="display-6 mb-5">
                    Personal Information
                </h1>
                <table>
                    <tr>
                        <td><h5>First Name</h5></td>
                        <td><h5><span class="badge bg-secondary">{{request.user.admission.firstname}}</span></h5></td>
                    </tr>
                    
                    <tr>
                        <td><h5>Middle Name</h5></td>
                        <td><h5><span class="badge bg-secondary">{{request.user.admission.middlename}}</span></h5></td>
                    </tr>
                    
                    <tr>
                        <td><h5>Last Name</h5></td>
                        <td><h5><span class="badge bg-secondary">{{request.user.admission.lastname}}</span></h5></td>
                    </tr>

                    <tr>
                        <td><h5>Date of Birth</h5></td>
                        <td><h5><span class="badge bg-secondary">{{request.user.admission.date_of_birth}}</span></h5></td>
                    </tr>
                    <tr>
                        <td><h5>Mobile Number</h5></td>
                        <td><h5><span class="badge bg-secondary">{{request.user.admission.mobile}}</span></h5></td>
                    </tr>

                    <tr>
                        <td><h5>Emergency Mobile Number</h5></td>
                        <td><h5><span class="badge bg-secondary">{{request.user.admission.emergency_mobile}}</span></h5></td>
                    </tr>
                    
                    <tr>
                        <td><h5>Present Address</h5></td>
                        <td><h5><span class="badge bg-secondary">{{request.user.admission.present_address}}</span></h5></td>
                    </tr>
                    <tr>
                        <td><h5>Present City</h5></td>
                        <td><h5><span class="badge bg-secondary">{{request.user.admission.present_city}}</span></h5></td>
                    </tr>
                    <tr>
                        <td><h5>Present State</h5></td>
                        <td><h5><span class="badge bg-secondary">{{request.user.admission.present_state}}</span></h5></td>
                    </tr>
                    <tr>
                        <td><h5>Present Zip Code</h5></td>
                        <td><h5><span class="badge bg-secondary">{{request.user.admission.present_zip}}</span></h5></td>
                    </tr>
                    <tr>
                        <td><h5>Current Package</h5></td>
                        <td><h5><span class="badge bg-secondary">{{request.user.admission.package_lpa}} LPA</span></h5></td>
                    </tr>
                </table>
            </li>
        </ul>
    </div>
{%endblock body %}

admission/templates/admission/studentprofile.html
{% extends 'admission/base.html' %}
{% block title %}Admission Portal{% endblock title%}
{% block student%}active{% endblock student%}
{% block body %}
{% include 'admission/msg.html' %}
    <center><h1 class="display-5">Register New Student</h1></center>
    <div class="container mt-5 mb-5">
        <center class="shadow-lg p-3 mb-5 bg-body rounded">
            <form action="{% url 'admission:student-profile' %}" method="POST">
                {% csrf_token %}

                <table class="table table-striped">
                    <tbody>
                        {% for f in form %}
                            <tr>
                                <th scope="row">{{f.label_tag}}</th>
                                <td>{{f}}</td>
                            </td>
                        {% endfor %} 
                    </tbody>
                  </table>
                
                
                <input type="submit" class="btn btn-success" value="Create new student profile" />
            </form>
        </center>
    </div>
{%endblock body %}