authsystem/urls.py
from django.urls import path
from authsystem.views import Index,Info,user_logout

app_name='authsystem'

urlpatterns = [
    path('', Index.as_view(), name='authsystem_index'),
    path('info/',Info.as_view(),name='authsystem_info'),
    path('logout/',user_logout,name='authsystem_logout')
]

finance/urls.py
from django.urls import path
from finance.views import(
    Index,FinanceProfile,AccountProfile,StudentProfile,StudentActivate,AcceptFee,
    SearchStudent,
) 


app_name = 'finance'
urlpatterns = [
    path('',Index.as_view(),name='index'),
    path('profile/',FinanceProfile.as_view(),name='profile'),
    path('account/',AccountProfile.as_view(),name='account'),
    path('studentprofile/',StudentProfile.as_view(),name='studentprofile'),
    path('studentactivate/<int:pk>/',StudentActivate.as_view(),name='studentactivate'),  
    path('feepayment/',AcceptFee.as_view(),name='payment'), 
    path('searchstudent/',SearchStudent.as_view(),name='search_student'),
]

xms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authsystem.urls')),
    path('student/',include('student.urls')),
    path('admission/',include('admission.urls')),
    path('clgstaff/',include('clgstaff.urls')),
    path('exam/',include('exam.urls')),
    path('finance/',include('finance.urls')),
    path('prof/',include('prof.urls')),
    path("sitemanager/",include('sitemanager.urls')),
    path('dean/',include('dean.urls'))
]

finance/models.py
from django.db import models
from authsystem.models import CustomUser

# Create your models here.

class FinanceSalary(models.Model):
    salary_date = models.DateField()
    salary_ammount = models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return f'self.id'
class FinanceDepartment(models.Model):
    firstname = models.CharField(max_length=255)
    middlename = models.CharField(max_length=255,blank=True)
    lastname = models.CharField(max_length=255)

    date_of_birth = models.DateField()
    mobile = models.CharField(max_length=10)
    emergency_mobile = models.CharField(max_length=10)
    
    present_address = models.CharField(max_length=255)
    present_city = models.CharField(max_length=255)
    present_state = models.CharField(max_length=255)
    present_zip = models.IntegerField()

    permanent_address = models.CharField(max_length=255)
    permanent_city = models.CharField(max_length=255)
    permanent_state = models.CharField(max_length=255)
    permanent_zip = models.IntegerField()
    account_type = models.CharField(default='',max_length=255)
    package_lpa = models.DecimalField(max_digits=10,decimal_places=2,default=0.0)
    salary = models.ForeignKey(FinanceSalary,on_delete = models.CASCADE,null= True,related_name='finance_salary')
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE,null=True,related_name='finance')
    def __str__(self):
        return f'{self.firstname} {self.lastname}'

finance/forms.py
from django import forms 
from finance.models import FinanceDepartment

ACCOUNT_TYPE = (
    ("finance","Staff"),
    ("finance manager","Manager"),
)

class FinanceForm(forms.ModelForm):
    account_type = forms.ChoiceField(label='Account Type' , choices=ACCOUNT_TYPE,widget=forms.Select(attrs={'class':'form-control mb-2'}))
    class Meta:
        model = FinanceDepartment
        exclude = ('user','salary')

        widgets = {
            'firstname':forms.TextInput(attrs={'placeholder':
            'First Name','class':'form-control mb-2'}),
            'middlename':forms.TextInput(attrs={'placeholder':
            'Middle Name','class':'form-control mb-2'}),
            'lastname':forms.TextInput(attrs={'placeholder':
            'Last Name','class':'form-control mb-5'}),
            'date_of_birth':forms.DateInput(attrs={'type':'date','class':'form-control mb-5'}),
            'mobile':forms.TextInput(attrs={'placeholder':
            'Mobile Number','class':'form-control mb-2'}),
            'emergency_mobile':forms.TextInput(attrs={'placeholder':
            'Emergency Mobile Number','class':'form-control mb-5'}),
            'present_address':forms.TextInput(attrs={'placeholder':
            'Present Address','class':'form-control mb-2'}),
            'present_city':forms.TextInput(attrs={'placeholder':
            'Present City','class':'form-control mb-2'}),
            'present_state':forms.TextInput(attrs={'placeholder':
            'Present State','class':'form-control mb-2'}),
            'present_zip':forms.TextInput(attrs={'placeholder':
            'Present Zip Code','class':'form-control mb-5'}),
            'permanent_address':forms.TextInput(attrs={'placeholder':
            'Permanent Address','class':'form-control mb-2'}),
            'permanent_city':forms.TextInput(attrs={'placeholder':
            'Permanent City','class':'form-control mb-2'}),
            'permanent_state':forms.TextInput(attrs={'placeholder':
            'Permanent State','class':'form-control mb-2'}),
            'permanent_zip':forms.TextInput(attrs={'placeholder':
            'Permanent Zip Code','class':'form-control mb-5'}),
            'package_lpa':forms.TextInput(attrs={'placeholder':
            'CTC LPA','class':'form-control mb-5'}),
        }

finance/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from finance.decorators import finance_required,finance_manager_required
from student.models import Student,CourseFee
from django.db.models import Q
from authsystem.models import CustomUser
from finance.forms import FinanceForm
from django.contrib.auth.models import Group
from django.contrib import messages
from datetime import datetime
class Index(View):
    @method_decorator(login_required)
    @method_decorator(finance_required)
    def get(self,request):
        return render(request,'finance/base.html',{})

class FinanceProfile(View):
    @method_decorator(login_required)
    @method_decorator(finance_required)
    def get(self,request):
        return render(request,'finance/profile.html',{})

class AccountProfile(View):
    @method_decorator(login_required)
    @method_decorator(finance_manager_required)
    def get(self,request):
        form = FinanceForm()
        return render(request,'finance/Account.html',{'form':form})

    @method_decorator(login_required)
    @method_decorator(finance_manager_required)
    def post(self,request):
        form_data = FinanceForm(request.POST)
        if form_data.is_valid():
            form_object = form_data.save()
            f_name = form_object.firstname
            l_name = form_object.lastname
            i_name = form_object.id
            mob = form_object.mobile
            dob = form_object.date_of_birth.year
            user_object = CustomUser.object.create_user(
                username=f'{f_name[:5].lower()}{l_name[:5].lower()}f{i_name}',
                password = f'{str(mob)[:5]}@{dob}'
            )
            user_object.groups.add(Group.objects.get(name=form_object.account_type))
            form_object.user = user_object
            form_object.save()
            messages.success(request,f'Profile created successfully : username {f_name[:5].lower()}{l_name[:5].lower()}f{i_name}')
        else:
            print("something is wrong")
        return redirect('finance:account')

class StudentProfile(View):
    @method_decorator(login_required)
    @method_decorator(finance_required)
    def get(self,request):
        # fetching all the student object who are not yet active
        student_names = CustomUser.object.filter(Q(is_active = False) & Q(groups__name='student'))
        return render(request,'finance/studentprofile.html',{'students':student_names}) 
    
class StudentActivate(View):
    @method_decorator(login_required)
    @method_decorator(finance_required)
    def get(self,request,pk):
        user_data = CustomUser.object.get(pk=pk)
        fee_details = CourseFee.objects.filter(student=user_data)
        total_fee = 0
        if fee_details.exists:
            for fee in fee_details:
                total_fee += fee.ammount
        return render(request,'finance/student_pay.html',{'user_data':user_data,'fee_paid':total_fee})


class AcceptFee(View):

    @method_decorator(login_required)
    @method_decorator(finance_required)
    def post(self,request):
        id = request.POST.get('id',None)
        fee = request.POST.get('fee',None)
        if id is not None and fee is not None:
            try:
                user_data = CustomUser.object.get(pk=id)
            except:
                messages.error(request,'Error')

            fee_object = CourseFee(student=user_data,date=datetime.now(),ammount=fee)
            fee_object.save()
            if user_data.is_active == 0:
                user_data.is_active = 1
                user_data.save()
            messages.success(request,'Data Saved Successfully')    

        return redirect('finance:studentactivate',pk=id)


class SearchStudent(View):
    def post(self,request):
        search_data = request.POST.get('search',None)
        data = Student.objects.filter(Q(firstname__in=search_data.split())| Q(lastname__icontains=search_data) | Q(id__icontains = search_data.split()) | Q(mobile = search_data) | Q(user__username__icontains=search_data))
        return render(request,'finance/student_search.html',{'data':data})

finance/templates/finance/Account.html
{% extends 'finance/base.html' %}
{% block title %}Finance Account{% endblock title%}
{% block staff%}active{% endblock staff%}
{% block body %}
    {% if messages %}
        <div class="container mb-5 mt-5">
            <center>
                {% for message in messages %}
                    {{message}}
                {% endfor %}
            </center>
        </div>
    {% endif %}
    <center><h1 class="display-5">Register a new Finance Staff</h1></center>
    <div class="container mt-5 mb-5">
        <center class="shadow-lg p-3 mb-5 bg-body rounded">
            <form action="{% url 'finance:account' %}" method="POST">
                {% csrf_token %}
                <table class="table table-striped">
                    <tbody>
                        {% for field in form %}
                        <tr>
                            <th>{{field.label_tag}}</th>
                            <td>{{field}}</td>
                          </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                  <input type="submit" value="Register" class="btn btn-success">
            </form>
        </center>
    </div>
{%endblock body %}

finance/templates/finance/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock%}</title>
  </head>
  <body>
    <!-- Nav Bar for Finance Portal -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'finance:index' %}">Finance</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% block student %} {% endblock %}" href="{% url 'finance:studentprofile' %}">Student Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block staff %} {% endblock %}" href="{% url 'finance:account' %}">New Finance Staff</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% block profile %} {% endblock %}" href="{% url 'finance:profile' %}">Profile</a>
              </li>
              <li class="nav-item mr-auto">
                <a class="btn btn-danger" href="{% url 'authsystem:authsystem_logout' %}">Logout</a>
              </li>
            </ul>
        </div>
      </nav>
    <!-- Navbar tag ended here-->

    <!-- Dynamic Render of HTML Body -->
    {% block body %}
    {% endblock %}
    <!-- End of Dynamic Render of HTML Body -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

finance/templates/finance/index.html
{% extends 'finance/base.html' %}
{% block title %}Finace Portal{% endblock title%}
{% block body %}
{% include 'admission/msg.html' %}
    <center><h1 class="display-5">Index Page</h1></center>
{%endblock body %}

finance/templates/finance/profile.html
{% extends 'finance/base.html' %}
{% block title %}Finance Profile{% endblock title%}
{% block profile%}active{% endblock profile%}
{% block body %}
    <center><h1 class="display-5">Hello in the finance Profile .This page will display the profile of the logged in finance manager</h1></center>
{%endblock body %}

finance/templates/finance/student_pay.html
{% extends 'finance/base.html' %}
{% load mathfilters %}
{% block title %}Student Profile{% endblock title%}
{% block staff%}active{% endblock staff%}
{% block body %}
  {% if messages %}
  <div class="container mb-5 mt-5">
    <center>
      {% for message in messages %}
        {{message}}
      {% endfor %}
    </center>
  </div>
  {% endif %}
    <div class="container mt-5 mb-5">
        <center>
            <h1 class="display-6 mb-5">Pay for tution fee for {{user_data.student_profile.user}} </h1>
        </center>
        <center>
            <table class="table table-striped" style="width:50%;">
                <tbody>
                  <tr>
                    <td>Id</td>
                    <td>{{user_data.id}}</td>
                  </tr>
                  <tr>
                    <td>First Name</td>
                    <td>{{user_data.student_profile.firstname}}</td>
                  </tr>
                  <tr>
                    <td>Last Name</td>
                    <td>{{user_data.student_profile.lastname}}</td>
                  </tr>
                  <tr>
                    <td>User Name</td>
                    <td>{{user_data.student_profile}}</td>
                  </tr>
                  <tr>
                    <td>Date of Birth</td>
                    <td>{{user_data.student_profile.date_of_birth}}</td>
                  </tr>
                  <tr>
                    <td>Course</td>
                    <td>{{user_data.student_profile.course}}</td>
                  </tr>
                  <tr>
                    <td>Total course fee</td>
                    <td>{{user_data.student_profile.actual_fee}}</td>
                  </tr>
                  <tr>
                    <td>Ammount to pay</td>
                    <td>{{user_data.student_profile.actual_fee|sub:fee_paid}}</td>
                  </tr>
                  <tr>
                    <td>Pay </td>
                    <td>
                        <form action="{% url 'finance:payment' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name='id' value={{user_data.id}} />
                            <input type="text" class="form-control mb-3" name="fee" />
                            <input type="submit" class="btn btn-success" value="Proceed with payment" />
                        </form>
                    </td>
                  </tr>
                  
                </tbody>
              </table>
        </center>
    </div>
{%endblock body %}

finance/templates/finance/student_search.html
{% extends 'finance/base.html' %}
{% block title %}Student Profile{% endblock title%}
{% block student%}active{% endblock student%}
{% block body %}

<div class="container mt-5">
    <center>
      <form action="{% url 'finance:search_student' %}" method="POST">
        {% csrf_token %}
          <input type='text' name='search' placeholder="Search Student" class="form-control shadow p-3 mb-5 bg-body rounded" />
          <input type="submit" value="Search" class="btn btn-primary mt-3"/>
      </form>
    </center>
</div>
<div class="container mt-3 mb-3">
  <hr>
</div>
{% if data %}
<div class="container mb-5 mt-5">
  <center>
      <h1 class="display-6 mb-5">Students List</h1>
      <table class="table">
          <thead>
            <tr>
              <th scope="col">Roll Number</th>
              <th scope="col">First Name</th>
              <th scope="col">last Name </th>
              <th scope="col">User Name</th>
              <th scope="col">Course Name</th>
              <th scope="col">Total Tution Fee</th>
              <th scope="col">Pay</th>
            </tr>
          </thead>
          <tbody>
              {% for student in data %}
              <tr>
                  <th scope="row">{{student.user.id}}</th>
                  <td>{{student.firstname}}</td>
                  <td>{{student.lastname}}</td>
                  <td>{{student.user}}</td>
                  <td>{{student.course}}</td>
                  <td>{{student.actual_fee}}</td>
                  <td><a href="{% url 'finance:studentactivate' student.user.id %}" class="btn btn-success">Pay</a></td>
              </tr>
              {% endfor %}
          </tbody>
        </table>
  </center>
</div>
{% else %}
  <div class="container">
    <div class="alert alert-primary shadow-lg p-3 mb-5 bg-body rounded" role="alert">
      No result found
    </div>
  </div>
{% endif %}

{%endblock body %}

finance/templates/finance/studentprofile.html
{% extends 'finance/base.html' %}
{% block title %}Student Profile{% endblock title%}
{% block student%}active{% endblock student%}
{% block body %}

    <div class="container mt-5">
        <center>
          <form action="{% url 'finance:search_student' %}" method="POST">
            {% csrf_token %}
              <input type='text' name='search' placeholder="Search Student" class="form-control shadow p-3 mb-5 bg-body rounded" />
              <input type="submit" value="Search" class="btn btn-primary mt-3"/>
          </form>
        </center>
    </div>
    <div class="container mt-3 mb-3">
      <hr>
    </div>
    <div class="container mb-5 mt-5">
        <center>
            <h1 class="display-6 mb-5">New Student List</h1>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Roll Number</th>
                    <th scope="col">First Name</th>
                    <th scope="col">last Name </th>
                    <th scope="col">User Name</th>
                    <th scope="col">Course Name</th>
                    <th scope="col">Total Tution Fee</th>
                    <th scope="col">Pay</th>
                  </tr>
                </thead>
                <tbody>
                    {% for student in students %}
                    <tr>
                        <th scope="row">{{student.id}}</th>
                        <td>{{student.student_profile.firstname}}</td>
                        <td>{{student.student_profile.lastname}}</td>
                        <td>{{student.student_profile.user}}</td>
                        <td>{{student.student_profile.course}}</td>
                        <td>{{student.student_profile.actual_fee}}</td>
                        <td><a href="{% url 'finance:studentactivate' student.id %}" class="btn btn-success">Pay</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
        </center>
    </div>
{%endblock body %}